import "./globals.css";
import NavbarBoot from "@/components/navbar/navbar";
// import SessionWrapper from "@/components/SessionWrapper";
import { ToastContainer } from "react-toastify";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <SessionWrapper>
    <html lang="en">
      <body>
        <NavbarBoot />
        {children}
        <ToastContainer />
      </body>
    </html>
    // </SessionWrapper>
  );
}
